#!/bin/sh

REPO_NAME=SDRPlusPlus

# Shell options
set -xe

# Clone repository
git clone --depth 1 https://github.com/AlexandreRouma/${REPO_NAME}
sleep 1

# Apply patch
patch -p0 -d ./${REPO_NAME} < ./usrp_enable.patch
echo "Applied patch."
sleep 1

# Build
mkdir ./${REPO_NAME}/build
sleep 0.1
cmake -S ./${REPO_NAME} -B ./${REPO_NAME}/build \
-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
-DOPT_BACKEND_GLFW=ON \
-DOPT_BACKEND_ANDROID=OFF \
-DOPT_OVERRIDE_STD_FILESYSTEM=OFF \
-DOPT_BUILD_AIRSPY_SOURCE=OFF \
-DOPT_BUILD_AIRSPYHF_SOURCE=OFF \
-DOPT_BUILD_AUDIO_SOURCE=OFF \
-DOPT_BUILD_BADGESDR_SOURCE=OFF \
-DOPT_BUILD_BLADERF_SOURCE=OFF \
-DOPT_BUILD_FILE_SOURCE=ON \
-DOPT_BUILD_FOBOSSDR_SOURCE=OFF \
-DOPT_BUILD_HACKRF_SOURCE=OFF \
-DOPT_BUILD_HAROGIC_SOURCE=OFF \
-DOPT_BUILD_HERMES_SOURCE=OFF \
-DOPT_BUILD_KCSDR_SOURCE=OFF \
-DOPT_BUILD_LIMESDR_SOURCE=OFF \
-DOPT_BUILD_NETWORK_SOURCE=ON \
-DOPT_BUILD_PERSEUS_SOURCE=OFF \
-DOPT_BUILD_PLUTOSDR_SOURCE=OFF \
-DOPT_BUILD_RFNM_SOURCE=OFF \
-DOPT_BUILD_RFSPACE_SOURCE=OFF \
-DOPT_BUILD_RTL_SDR_SOURCE=OFF \
-DOPT_BUILD_RTL_TCP_SOURCE=OFF \
-DOPT_BUILD_SDRPP_SERVER_SOURCE=ON \
-DOPT_BUILD_SDRPLAY_SOURCE=OFF \
-DOPT_BUILD_SOAPY_SOURCE=OFF \
-DOPT_BUILD_SPECTRAN_SOURCE=OFF \
-DOPT_BUILD_SPECTRAN_HTTP_SOURCE=OFF \
-DOPT_BUILD_SPYSERVER_SOURCE=ON \
-DOPT_BUILD_USRP_SOURCE=ON \
-DOPT_BUILD_ANDROID_AUDIO_SINK=OFF \
-DOPT_BUILD_AUDIO_SINK=OFF \
-DOPT_BUILD_NETWORK_SINK=ON \
-DOPT_BUILD_NEW_PORTAUDIO_SINK=ON \
-DOPT_BUILD_PORTAUDIO_SINK=ON \
-DOPT_BUILD_ATV_DECODER=OFF \
-DOPT_BUILD_DAB_DECODER=OFF \
-DOPT_BUILD_FALCON9_DECODER=OFF \
-DOPT_BUILD_KG_SSTV_DECODER=OFF \
-DOPT_BUILD_M17_DECODER=OFF \
-DOPT_BUILD_METEOR_DEMODULATOR=ON \
-DOPT_BUILD_PAGER_DECODER=ON \
-DOPT_BUILD_RADIO=ON \
-DOPT_BUILD_RYFI_DECODER=OFF \
-DOPT_BUILD_VOR_RECEIVER=OFF \
-DOPT_BUILD_WEATHER_SAT_DECODER=OFF \
-DOPT_BUILD_DISCORD_PRESENCE=ON \
-DOPT_BUILD_FREQUENCY_MANAGER=ON \
-DOPT_BUILD_IQ_EXPORTER=ON \
-DOPT_BUILD_RECORDER=ON \
-DOPT_BUILD_RIGCTL_CLIENT=ON \
-DOPT_BUILD_RIGCTL_SERVER=ON \
-DOPT_BUILD_SCANNER=ON \
-DOPT_BUILD_SCHEDULER=OFF \
-DUSE_INTERNAL_LIBCORRECT=ON \
-DUSE_BUNDLE_DEFAULTS=ON \
-DCOPY_MSVC_REDISTRIBUTABLES=OFF
sleep 1
cmake --build ./${REPO_NAME}/build
sleep 1

# Create bundle
cd ./${REPO_NAME}
sleep 0.1
sh ./make_macos_bundle.sh ./build ./SDR++.app
sleep 1
mv ./SDR++.app ../
sleep 0.1
cd ../
sleep 1

# Remove repository
rm -rf ./${REPO_NAME}
echo "Build Completed."