name: "Build test"

# 手動で実行
on: workflow_dispatch

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake pkgconf fftw glfw volk uhd portaudio

      - name: Build
        working-directory: ${{runner.workspace}}
        run: sh build.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Apple(Arm)-binary
          path: ${{runner.workspace}}/SDR++.app